
##### Configuration #####
BARCODES = config["barcodes"].split(",")
TAXA = config["taxa"].split(",")

##### Target rules #####

rule all:
    input:
        expand(config["output_path"] + "taxon/barcode_{barcode}/{taxon}.ids", barcode=BARCODES, taxon=TAXA),

##### Modules #####
include: "rules/bin.smk"
