name: rampart-coi
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.73
  - coreutils=8.25
  - nodejs=12.11.1
  - minimap2=2.17
  - pandas=0.25.2
  - pip=19.3.1
  - python=3.6
  - snakemake=5.7.1
  - medaka=0.10.0
  - artic-network::rampart
  - kraken2=2.0.8-beta
  - krona=2.7.1=pl526_0
  - watchdog=0.8.3=py36_0
  - yarn=1.10.1
  - curl
  - cmake
  - sed
  - numpy=1.16
  - pip:
    - msgpack==0.6.2
    - binlorry==1.1.0
    - git+https://github.com/artic-network/Porechop.git@v0.3.1pre

