name: rampart-coi
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.73
  - pandas=0.23.0=py36_1
  - python=3.6.6
  - minimap2=2.11
  - snakemake=5.4.3
  - kraken2=2.0.8-beta
  - snakemake=5.4.3
  - krona=2.7.1
  - watchdog=0.8.3=py36_0
  - yarn=1.10.1
  - nodejs=10.4.1
  - pip=19.1
  - pip:
    - msgpack==0.5.6
    - binlorry==1.0.0

