##### Where is the data? #####

input_path: path/to/bin #where rampart will find the reads
output_path: path/to/binned #where rampart will put the binned/ filtered files 

references: references.fasta
config: config_file


##### Read thresholds #####

min_reads: 100
min_pcent: 2

##### Barcodes to process #####

sample: 
barcodes: BCXX,BCYY

##### Analysis Stem #####
