input_path: path/to/data #where rampart will find the data (basecalled reads)
output_path: path/to/default_output

min_length: 1
max_length: 100000

barcode: NBXX

filename_stem:

kraken_db: "/Users/rmcolq/VirusEvolution Dropbox/Rachel Colquhoun/Projects/Seawater_WIMP/db/bold"
