configfile: "../protocols/pipelines/kraken/config.yaml" #relative to annotator.js script


##### Target rules #####

SAMPLES = [config['filename_stem']]
BARCODES = config['barcodes'].strip().split(",")

rule all:
    input:
        expand( config["outputPath"] + "/classified/barcode_{barcode}/{sample}.kraken", sample=SAMPLES, barcode=BARCODES)
        #output of this pipeline is kraken classifications for this filename_stem, split by barcode and an updated Krona
        #plot summary.

##### Modules #####
include: "rules/kraken.smk"


