
##### Configuration #####

BARCODES = config["barcodes"].split(',')

barcode_string = ""
for i in BARCODES:
    barcode_string+=" {}".format(i.lstrip("NB").lstrip("BC").lstrip("barcode"))

BARCODES.append('none')
barcode_string_with_none = ""
for i in BARCODES:
    barcode_string_with_none+=" {}".format(i)

if config["references_file"][0] != "/":
    config["references_file"] = workflow.basedir + "/../../" + config["references_file"]

if config["kraken_db"][0] != "/":
    config["kraken_db"] = workflow.basedir + "/../../" + config["kraken_db"]
##### Target rules #####

rule all:
    input:
        expand(config["output_path"]+ "{filename_stem}.csv", filename_stem=config["filename_stem"]),
        expand(config["output_path"]+ "classified/barcode_{barcode}/{filename_stem}.kraken", filename_stem=config["filename_stem"], barcode=BARCODES)

##### Modules #####
include: "rules/demultiplex.smk"
include: "rules/map.smk"
include: "rules/bin.smk"
include: "rules/kraken.smk"
