#Where is the data and where should it be put

input_path: path/to/data #where rampart will find the data
output_path: path/to/data #where rampart will put the data

#Binlorry params
min_length: 1
max_length: 10000

#Barcode format BCXX
barcodes: none

min_count: 100

kraken_fasta: 

taxon_names: 
taxids: 
