
##### Configuration #####
BARCODES = config["barcodes"].split(",")
TAXA = []
for taxon in config["taxa"].split(","):
    TAXA.append("_".join(taxon.split()))

##### Target rules #####

rule all:
    input:
        expand(config["output_path"] + "taxids/barcode_{barcode}/config.yaml", barcode=BARCODES),

##### Modules #####
include: "rules/bin.smk"
