##### Configuration #####

barcodes = config["barcodes"].split(',')
barcode_string = ""
for i in barcodes:
    barcode_string+=" {}".format(i)

sample_string = ""
if config["sample"]:
    sample_string = config["sample"]
else:
    sample_string = "_".join(barcodes)
    config["sample"]=sample_string
    
##### Target rules #####

rule all:
    input:
        expand(config["output_path"] + "/binned_{sample}.fastq",sample=config["sample"])
        #output of this pipeline is both the fastq file and a csv report of the reads in that file, with respective annotations.

##### Modules #####

include: "rules/bin.smk"


